# Generated by Django 4.2.2 on 2023-06-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("spending_this_month", models.IntegerField()),
                ("expected_spending_this_month", models.IntegerField()),
                ("percentage_over_under_this_month", models.FloatField()),
            ],
        ),
    ]
